#!/bin/bash


# while
num=0

while [ $num -le 10 ]; do
	echo $num
	num=$((num + 1))
done

num=0

while [ $num -le 20 ]; do
	if (( (( $num % 2 )) == 0 )); then
		num=$((num + 1))
		continue
	fi

	if ((num >= 15)); then
		break
	fi

	echo $num
	num=$((num + 1))
done


until [ $num -gt 10 ]; do
	echo $num
	$num=$((num+1))
done


# for
for (( i=0; i <= 10; i=i+1 )); do
	echo $i
done

for i in {A..Z}; do
	echo $i
done


