#!/bin/bash

# shell scripting tutorial via Derek Banas youtube channel

# some usefull vim quick reference stuff:

# KEYBINDINGS
#		select: shift-v
#		insert: i
#		append: a
#		delete: d
#		copy: y
#		paste: shift-p
#	STUFF
#		show .vimrc file currently in use: :echo $MYVIMRC
#		write file: :w
#		quit file: :q
#		write and quit: :x

# Comment

echo "Hello world"

# Constant
declare -r NUM1=5

# Variables

myName="David"

num2=4
num3=$((NUM1+num2))
num4=$((NUM1-num2))
num5=$((NUM1*num2))
num6=$((NUM1/num2))

echo "5 + 4 = $num3"
echo "5 - 4 = $num4"
echo "5 * 4 = $num5"
echo "5 / 4 = $num6"

echo $((5**2))

echo $(( 5%4 ))

rand=5
let rand+=4 # also -=, *=, /=, etc...
echo "$rand"


echo "rand++ = $(( rand++ ))"
echo "++rand = $(( ++rand ))"
echo "rand-- = $(( rand-- ))"
echo "--rand = $(( --rand ))"

num7=1.2
num8=3.4
num9=$(python -c "print($num7+$num8)")
echo $num9


cat<< END
This text
prints on
many Lines
END



# Functions

getDate() {
	date

	return
}

getDate


name="Derek"

demLocal() {
	local name="Paul"
	return
}

demLocal

echo "$name"



getSum() {
	# paramaters are $1, $2, $3, etc...
	local num3=$1
	local num4=$2
	
	local sum=$((num3+num4))

	echo $sum
}

num1=5
num2=6

sum=$(getSum num1 num2)
echo "The sum is $sum"


# GET USER INPUT

read -p "What is your name? " name

echo "Hello $name"


# CONDITIONALS

read -p "How old are you? " age

if [ $age -ge 16 ] # ==-eq, !=-ne, <=-le, <-lt, >=-ge, >-gt
then
	echo "You can drive"
elif [ $age -eq 15 ]
then
	echo "You can drive next year"
else
	echo "You can't drive"
fi


read -p "Enter a number : " num

if ((num == 10)); then
	echo "Your number equals 10"
fi

if ((num > 10)); then
	echo "It is greater than 10"
else
	echo "It is is less than or equal to 10"
fi


if (( ((num % 2)) == 0)); then
	echo "It is even"
fi



if (( ((num > 0)) && ((num < 11 )) )); # ||-or, !-not, etc.
then
	echo "$num is between 1 and 10"
fi



touch samp_file && vim samp_file


[ -d samp_dir ] || mkdir samp_dir



# STRINGS
str1=""
str2="Sad"
str3="Happy"

echo "str1 = $str1"
echo "str2 = $str2"
echo "str3 = $str3"


if [ "$str1" ]; then
	echo "$str1 is not null"
fi

if [ -z "$str1" ]; then
	echo "str1 has no value"
fi

if [ "$str2" == "$str3"]; then
	echo "$str2 equals $str3"
elif [ "$str2" != "$str3" ]; then
	echo "$str2 is not equal to $str3"
fi


if [ "$str2" > "$str3" ]; then
	echo "$str2 is greater than $str3"
elif [ "$str2" < "$str3" ]; then
	echo "$str2 is less than $str3"
fi













