#!/bin/bash

read -p "Vallidate Date : " date

pat="^[0-9]{8}$"

if [[ $date =~ $pat ]]; then
	echo "$date is valid"
else
	echo "$date not valid"
fi

read -p "enter two numbers to sum : " num1 num2

sum=$((num1+num2))


echo "$num1 + $num2 = $sum"


read -sp "Enter the secret code " secret

if [ "$secret" == "password" ]; then
	echo "Enter"
else
	echo "Wrong password"
fi

OIFS="$IFS"

IFS=","

read -p "Enter 2 numbers to add separated by a comma " num1 num2

# accept commas and whitespace
num1=${num1//[[:blank:]]/}
num2=${num2//[[:blank:]]/}

sum=$((num1+num2))

echo "$num1 + $num2 = $sum"

IFS="$OIFS"
